# based on https://github.com/ogra1/snapd-docker
FROM ubuntu:25.10

ENV container=docker
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV SNAPPY_LAUNCHER_INSIDE_TESTS=true

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y fuse init snapd squashfuse sudo

RUN dpkg-divert --local --rename --add /sbin/udevadm
RUN ln -s /bin/true /sbin/udevadm
RUN systemctl enable snapd snapd.seeded
VOLUME ["/sys/fs/cgroup"]
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk-3-0 libegl1 libgles2 xvfb

# Flutter's Linux build toolchain, which the snap no longer bundles.
# clang links against GCC's libstdc++, so install g++ too.
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang cmake ninja-build g++ pkg-config libgtk-3-dev

# https://github.com/diddlesnaps/snapcraft-container/pull/17
RUN dpkg-divert --local --rename --add /usr/bin/systemd-detect-virt
ADD systemd-detect-virt /usr/bin/
