# based on https://github.com/ogra1/snapd-docker
FROM ubuntu:23.10

ENV container docker
ENV PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV SNAPPY_LAUNCHER_INSIDE_TESTS true

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y fuse init snapd squashfuse sudo

RUN dpkg-divert --local --rename --add /sbin/udevadm
RUN ln -s /bin/true /sbin/udevadm
RUN systemctl enable snapd snapd.seeded
VOLUME ["/sys/fs/cgroup"]
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk-3-0 libegl1 xvfb

# https://github.com/diddlesnaps/snapcraft-container/pull/17
RUN dpkg-divert --local --rename --add /usr/bin/systemd-detect-virt
ADD systemd-detect-virt /usr/bin/
