name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: classic
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  flutter:
    command: flutter.sh
  openurl:
    command: openurl.sh
    desktop: flutter.desktop
  dart:
    command: dart.sh

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp dart.sh $SNAPCRAFT_PART_INSTALL/
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
      cp env.sh $SNAPCRAFT_PART_INSTALL/
      cp openurl.sh $SNAPCRAFT_PART_INSTALL/
      cp flutter.desktop $SNAPCRAFT_PART_INSTALL/

      ENV_SH=$SNAPCRAFT_PART_INSTALL/env.sh
      sed -i 's#<SNAPCRAFT_ARCH_TRIPLET>#$SNAPCRAFT_ARCH_TRIPLET#' $ENV_SH
    stage-packages:
      - jq
      - xz-utils
      - git
      - curl
      - unzip
      - clang
      - libstdc++-8-dev
      - cmake
      - ninja-build
      - rsync
      - libglu1-mesa
      - libgtk-3-dev
      - libgtk-3-0
      - pkg-config
      - libc6
      - libc6-dev
      - libc-bin
      - libblkid-dev
      - libblkid1
      - liblzma-dev
      - liblzma5
      - libgcrypt20-dev
      - libstdc++6
      - libpcre3
      - on amd64: [ i965-va-driver ]
      - libgcrypt20
      - libglib2.0-dev
      - libglib2.0-0
      - libdbus-1-3
      - libexpat1
      - libffi6
    prime:
      - -lib32
      - -libx32
      - -usr/lib32
      - -usr/libx32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*
      - -usr/share/doc
      - -usr/share/man
      - -usr/include/c++/6*
      - -usr/include/*/c++/6*
      - -usr/include/c++/7*
      - -usr/include/*/c++/7*
      - -usr/lib/gcc/*/6

  # Fix pkgconfig files
  pkgconfig:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
        sed -i 's#prefix=$SNAPCRAFT_STAGE#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current#' $PC
        sed -i 's#prefix = /usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#prefix=/usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#original_prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#original_prefix=/usr#' $PC

        sed -i 's#libdir=/usr#libdir=${prefix}#' $PC
        sed -i 's#libdir=/lib#libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib#' $PC

        sed -i 's#exec_prefix=/usr#exec_prefix=${prefix}#' $PC
        sed -i 's#includedir=/usr#includedir=${prefix}#' $PC
        sed -i 's#sysconfdir=/etc#sysconfdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/etc#' $PC

        sed -i 's#/usr/#/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/#g' $PC
        sed -i 's#/etc/#/snap/$SNAPCRAFT_PROJECT_NAME/current/etc/#g' $PC
      done

  # Fix linker files
  linker:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux

      find . -type l -name "*.so*" -exec bash -c 'if [[ $(readlink $1) == /* ]] && [[ $(readlink $1) != /snap* ]]; then ln -sf /snap/flutter/current$(readlink $1) $1; fi' bash {} \;

      for so in usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc.so usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpthread.so usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libm.so
      do
        if [ -f $SNAPCRAFT_PRIME/$so ]; then
          sed -i "$SNAPCRAFT_PRIME/${so}" \
              -e "s# /lib/$SNAPCRAFT_ARCH_TRIPLET# /snap/$SNAPCRAFT_PROJECT_NAME/current/lib/$SNAPCRAFT_ARCH_TRIPLET#g" \
              -e "s# \(/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/.*\)# /snap/$SNAPCRAFT_PROJECT_NAME/current\1#g"
        fi
      done
