name: flutter
base: core18
version: git
summary: Flutter
description: |
  Flutter is Google’s UI toolkit for building beautiful, natively compiled
  applications for mobile, web, and desktop from a single codebase.

grade: stable
confinement: classic
architectures:
  - build-on: amd64

apps:
  flutter:
    command: flutter.sh
  openurl:
    command: openurl.sh
    desktop: flutter.desktop

parts:
  flutter:
    plugin: nil
    source: .
    override-build: |
      cp flutter.sh $SNAPCRAFT_PART_INSTALL/
      cp env.sh $SNAPCRAFT_PART_INSTALL/
      cp openurl.sh $SNAPCRAFT_PART_INSTALL/
      cp flutter.desktop $SNAPCRAFT_PART_INSTALL/

      ENV_SH=$SNAPCRAFT_PART_INSTALL/env.sh
      sed -i 's#<SNAPCRAFT_ARCH_TRIPLET>#$SNAPCRAFT_ARCH_TRIPLET#' $ENV_SH
    stage-packages:
      - jq
      - xz-utils
      - git
      - curl
      - unzip
      - clang
      - libstdc++-8-dev
      - cmake
      - ninja-build
      - rsync
      - libglu1-mesa
      - libgtk-3-dev
      - pkg-config
      - libc6
      - libc-bin
      - libblkid-dev
      - liblzma-dev

    prime:
      - -lib32
      - -libx32
      - -usr/lib32
      - -usr/libx32
      - -usr/lib/llvm-6.0/lib/clang/6.0.0/lib/linux/*i386*
      - -usr/share/doc
      - -usr/share/man
      - -usr/include/c++/6*
      - -usr/include/*/c++/6*
      - -usr/include/c++/7*
      - -usr/include/*/c++/7*
      - -usr/lib/gcc/*/6

  # Fix pkgconfig files
  pkgconfig:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for PC in $(find . -path "*/pkgconfig/*.pc")
      do
        sed -i 's#prefix=$SNAPCRAFT_STAGE#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current#' $PC
        sed -i 's#prefix = /usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#prefix=/usr#prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#' $PC
        sed -i 's#original_prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr#original_prefix=/usr#' $PC

        sed -i 's#libdir=/usr#libdir=${prefix}#' $PC
        sed -i 's#libdir=/lib#libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib#' $PC

        sed -i 's#exec_prefix=/usr#exec_prefix=${prefix}#' $PC
        sed -i 's#includedir=/usr#includedir=${prefix}#' $PC
        sed -i 's#sysconfdir=/etc#sysconfdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/etc#' $PC

        sed -i 's#/usr/#/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/#g' $PC
        sed -i 's#/etc/#/snap/$SNAPCRAFT_PROJECT_NAME/current/etc/#g' $PC
      done

  # Fix linker files
  linker:
    after: [flutter]
    plugin: nil
    override-prime: |
      set -eux
      for so in usr/lib/x86_64-linux-gnu/libc.so usr/lib/x86_64-linux-gnu/libpthread.so usr/lib/x86_64-linux-gnu/libm.so
      do
        sed -i "${so}" \
            -e "s# /lib/x86_64-linux-gnu# /snap/$SNAPCRAFT_PROJECT_NAME/current/lib/x86_64-linux-gnu#g" \
            -e "s# \(/usr/lib/x86_64-linux-gnu/.*\)# /snap/$SNAPCRAFT_PROJECT_NAME/current\1#g"
      done
